server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/java_test'
    username: 'postgres'
    password: 'speelberg'
    driver-class-name: 'org.postgresql.Driver'

jpa:
  show-sql: true

